api = "0.8"

[buildpack]
id = "heroku/procfile"
version = "2.0.0"
name = "Procfile"
homepage = "https://github.com/heroku/procfile-cnb"
description = "Official Heroku buildpack for using Procfile."
keywords = ["procfile", "processes"]

[[stacks]]
id = "*"

[[buildpack.licenses]]
type = "BSD-3-Clause"

[metadata]
[metadata.release]
[metadata.release.docker]
repository = "docker.io/heroku/procfile-cnb"