api = "0.10"

[buildpack]
id = "heroku/procfile"
version = "4.0.0"
name = "Heroku Procfile"
homepage = "https://github.com/heroku/buildpacks-procfile"
description = "Heroku's Procfile buildpack."
keywords = ["procfile", "processes", "heroku"]

[[buildpack.licenses]]
type = "BSD-3-Clause"

[[targets]]
os = "linux"
arch = "amd64"

[[targets]]
os = "linux"
arch = "arm64"

[metadata.release]
image = { repository = "docker.io/heroku/buildpack-procfile" }
