api = "0.10"

[buildpack]
id = "heroku/procfile"
version = "2.0.2"
name = "Heroku Procfile"
homepage = "https://github.com/heroku/procfile-cnb"
description = "Heroku's Procfile buildpack."
keywords = ["procfile", "processes", "heroku"]

[[buildpack.licenses]]
type = "BSD-3-Clause"

[[stacks]]
id = "*"

[[targets]]
os = "linux"
arch = "amd64"

[metadata.release]
image = { repository = "docker.io/heroku/procfile-cnb" }
